/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jerry_ndk_FFmpegUtil */

#ifndef _Included_com_jerry_ndk_FFmpegUtil
#define _Included_com_jerry_ndk_FFmpegUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jerry_ndk_FFmpegUtil
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jerry_ndk_FFmpegUtil_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
